image: debian:stable

before_script:
  - apt update -qq
  - apt install -y -qq autoconf automake autopoint dh-autoreconf cppcheck gettext autoconf pkg-config libtool m4 autotools-dev perl
  - apt install -y -qq help2man asciidoctor asciidoc-base
  - apt install -y -qq libsensors4-dev libgtop2-dev libudisks2-dev libatasmart-dev libxnvctrl-dev 
  - apt install -y -qq libgtk-3-dev libnotify-dev libappindicator3-dev
  - apt install -y -qq libmicrohttpd-dev libjson-c-dev libcurl4-gnutls-dev
  - autoreconf -i

stages:
  - build

build-check:
  stage: build
  script:
    - ./configure
    - make clean all
    - make check

build-distcheck:
  stage: build
  script:
    - ./configure
    - make clean all
    - make distcheck
