image: debian:unstable

before_script:
  - apt update -qq
  - apt install -y -qq build-essential autoconf automake pkg-config libtool m4 autoconf-archive autotools-dev  

stages:
  - build

build-distcheck:
  stage: build
  script:
    - autoreconf -i
    - make clean all
