image: debian:unstable

before_script:
  - apt update -qq
  - apt install -y -qq autoconf\
 automake\
 autopoint\
 dh-autoreconf\
 cppcheck\
 gettext\
 help2man\
 libsensors4-devbuild-essential\
 autoconf\
 pkg-config\
 libtool\
 m4\
 autotools-dev  

stages:
  - build

build-distcheck:
  stage: build
  script:
    - autoreconf -i
    - make clean all
